### ISSUE TITLE
Plotting: AssertionError: var should be in trace.varnames

### ISSUE THREAD

**Issue by wmf1991yeah** [Priesemann-Group/covid19_inference#57]
I meet a problem when I run "example_what_if.ipynb" using my own data. When I run fig, axes = cov19.plot.timeseries_overview(), An error displays: "AssertionError: var should be in trace.varnames". The error is as follow:
![image](https://user-images.githubusercontent.com/30073218/94142201-776bd700-fea0-11ea-812e-5d92e9de50d7.png)
How to address the problem? Ask for help.

**Comment by semohr** [comment]
I dont know how your model looks but you do have to use our variable names if you want to use these high level plotting functions. As far as I remember the pymc3 name for the new cases has to be `"new_cases"`  otherwise the timeseries_overview plotting will not work.

You could also change `"new_cases"` to your variable name [here](https://github.com/Priesemann-Group/covid19_inference/blob/ba859e601a57c2a1e0e74802aae04a918e4d58c0/covid19_inference/plot.py#L215-L217) or [here](https://github.com/Priesemann-Group/covid19_inference/blob/ba859e601a57c2a1e0e74802aae04a918e4d58c0/scripts/example_what_if.py#L138) in the what if script.

I hope this helps you to understand your problem.

**Comment by wmf1991yeah** [comment]
I use your SIR model and I don't change all default variable names.

**Comment by semohr** [comment]
Hmm this is quite strange than, I'm going to test it.

**Comment by wmf1991yeah** [comment]
Oh! I know, I cancel the weekend modulation because I don't need the weekend modulation. When I add the line of code. It can run correctly.
![image](https://user-images.githubusercontent.com/30073218/94148211-eb11e200-fea8-11ea-8815-47532eeb845a.png)
However, We really don't need the weekend modulation for Chinese CDC. How to cancel the weekend modulation at the same time, assure the correct variable name "new_cases"?

**Comment by semohr** [comment]
I see :+1: 

You can just change the name in this line from `"delayed_cases"` to `"new_cases"` and it should work.
```python
        new_cases = cov19.model.delay_cases(
            cases=new_cases,
            name_cases="delayed_cases",
            pr_mean_of_median=pr_delay,
            pr_median_of_width=0.3,
        )
```

**Comment by wmf1991yeah** [comment]
I see. Thank you very much!
